require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AdvertisementCampaignsController do

  # This should return the minimal set of attributes required to create a valid
  # AdvertisementCampaign. As you add validations to AdvertisementCampaign, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AdvertisementCampaignsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all advertisement_campaigns as @advertisement_campaigns" do
      advertisement_campaign = AdvertisementCampaign.create! valid_attributes
      get :index, {}, valid_session
      assigns(:advertisement_campaigns).should eq([advertisement_campaign])
    end
  end

  describe "GET show" do
    it "assigns the requested advertisement_campaign as @advertisement_campaign" do
      advertisement_campaign = AdvertisementCampaign.create! valid_attributes
      get :show, {:id => advertisement_campaign.to_param}, valid_session
      assigns(:advertisement_campaign).should eq(advertisement_campaign)
    end
  end

  describe "GET new" do
    it "assigns a new advertisement_campaign as @advertisement_campaign" do
      get :new, {}, valid_session
      assigns(:advertisement_campaign).should be_a_new(AdvertisementCampaign)
    end
  end

  describe "GET edit" do
    it "assigns the requested advertisement_campaign as @advertisement_campaign" do
      advertisement_campaign = AdvertisementCampaign.create! valid_attributes
      get :edit, {:id => advertisement_campaign.to_param}, valid_session
      assigns(:advertisement_campaign).should eq(advertisement_campaign)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new AdvertisementCampaign" do
        expect {
          post :create, {:advertisement_campaign => valid_attributes}, valid_session
        }.to change(AdvertisementCampaign, :count).by(1)
      end

      it "assigns a newly created advertisement_campaign as @advertisement_campaign" do
        post :create, {:advertisement_campaign => valid_attributes}, valid_session
        assigns(:advertisement_campaign).should be_a(AdvertisementCampaign)
        assigns(:advertisement_campaign).should be_persisted
      end

      it "redirects to the created advertisement_campaign" do
        post :create, {:advertisement_campaign => valid_attributes}, valid_session
        response.should redirect_to(AdvertisementCampaign.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved advertisement_campaign as @advertisement_campaign" do
        # Trigger the behavior that occurs when invalid params are submitted
        AdvertisementCampaign.any_instance.stub(:save).and_return(false)
        post :create, {:advertisement_campaign => { "name" => "invalid value" }}, valid_session
        assigns(:advertisement_campaign).should be_a_new(AdvertisementCampaign)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        AdvertisementCampaign.any_instance.stub(:save).and_return(false)
        post :create, {:advertisement_campaign => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested advertisement_campaign" do
        advertisement_campaign = AdvertisementCampaign.create! valid_attributes
        # Assuming there are no other advertisement_campaigns in the database, this
        # specifies that the AdvertisementCampaign created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        AdvertisementCampaign.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => advertisement_campaign.to_param, :advertisement_campaign => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested advertisement_campaign as @advertisement_campaign" do
        advertisement_campaign = AdvertisementCampaign.create! valid_attributes
        put :update, {:id => advertisement_campaign.to_param, :advertisement_campaign => valid_attributes}, valid_session
        assigns(:advertisement_campaign).should eq(advertisement_campaign)
      end

      it "redirects to the advertisement_campaign" do
        advertisement_campaign = AdvertisementCampaign.create! valid_attributes
        put :update, {:id => advertisement_campaign.to_param, :advertisement_campaign => valid_attributes}, valid_session
        response.should redirect_to(advertisement_campaign)
      end
    end

    describe "with invalid params" do
      it "assigns the advertisement_campaign as @advertisement_campaign" do
        advertisement_campaign = AdvertisementCampaign.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AdvertisementCampaign.any_instance.stub(:save).and_return(false)
        put :update, {:id => advertisement_campaign.to_param, :advertisement_campaign => { "name" => "invalid value" }}, valid_session
        assigns(:advertisement_campaign).should eq(advertisement_campaign)
      end

      it "re-renders the 'edit' template" do
        advertisement_campaign = AdvertisementCampaign.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AdvertisementCampaign.any_instance.stub(:save).and_return(false)
        put :update, {:id => advertisement_campaign.to_param, :advertisement_campaign => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested advertisement_campaign" do
      advertisement_campaign = AdvertisementCampaign.create! valid_attributes
      expect {
        delete :destroy, {:id => advertisement_campaign.to_param}, valid_session
      }.to change(AdvertisementCampaign, :count).by(-1)
    end

    it "redirects to the advertisement_campaigns list" do
      advertisement_campaign = AdvertisementCampaign.create! valid_attributes
      delete :destroy, {:id => advertisement_campaign.to_param}, valid_session
      response.should redirect_to(advertisement_campaigns_url)
    end
  end

end
