require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TeaserBlocksController do

  # This should return the minimal set of attributes required to create a valid
  # TeaserBlock. As you add validations to TeaserBlock, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "topic" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TeaserBlocksController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all teaser_blocks as @teaser_blocks" do
      teaser_block = TeaserBlock.create! valid_attributes
      get :index, {}, valid_session
      assigns(:teaser_blocks).should eq([teaser_block])
    end
  end

  describe "GET show" do
    it "assigns the requested teaser_block as @teaser_block" do
      teaser_block = TeaserBlock.create! valid_attributes
      get :show, {:id => teaser_block.to_param}, valid_session
      assigns(:teaser_block).should eq(teaser_block)
    end
  end

  describe "GET new" do
    it "assigns a new teaser_block as @teaser_block" do
      get :new, {}, valid_session
      assigns(:teaser_block).should be_a_new(TeaserBlock)
    end
  end

  describe "GET edit" do
    it "assigns the requested teaser_block as @teaser_block" do
      teaser_block = TeaserBlock.create! valid_attributes
      get :edit, {:id => teaser_block.to_param}, valid_session
      assigns(:teaser_block).should eq(teaser_block)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new TeaserBlock" do
        expect {
          post :create, {:teaser_block => valid_attributes}, valid_session
        }.to change(TeaserBlock, :count).by(1)
      end

      it "assigns a newly created teaser_block as @teaser_block" do
        post :create, {:teaser_block => valid_attributes}, valid_session
        assigns(:teaser_block).should be_a(TeaserBlock)
        assigns(:teaser_block).should be_persisted
      end

      it "redirects to the created teaser_block" do
        post :create, {:teaser_block => valid_attributes}, valid_session
        response.should redirect_to(TeaserBlock.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved teaser_block as @teaser_block" do
        # Trigger the behavior that occurs when invalid params are submitted
        TeaserBlock.any_instance.stub(:save).and_return(false)
        post :create, {:teaser_block => { "topic" => "invalid value" }}, valid_session
        assigns(:teaser_block).should be_a_new(TeaserBlock)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        TeaserBlock.any_instance.stub(:save).and_return(false)
        post :create, {:teaser_block => { "topic" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested teaser_block" do
        teaser_block = TeaserBlock.create! valid_attributes
        # Assuming there are no other teaser_blocks in the database, this
        # specifies that the TeaserBlock created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        TeaserBlock.any_instance.should_receive(:update).with({ "topic" => "MyString" })
        put :update, {:id => teaser_block.to_param, :teaser_block => { "topic" => "MyString" }}, valid_session
      end

      it "assigns the requested teaser_block as @teaser_block" do
        teaser_block = TeaserBlock.create! valid_attributes
        put :update, {:id => teaser_block.to_param, :teaser_block => valid_attributes}, valid_session
        assigns(:teaser_block).should eq(teaser_block)
      end

      it "redirects to the teaser_block" do
        teaser_block = TeaserBlock.create! valid_attributes
        put :update, {:id => teaser_block.to_param, :teaser_block => valid_attributes}, valid_session
        response.should redirect_to(teaser_block)
      end
    end

    describe "with invalid params" do
      it "assigns the teaser_block as @teaser_block" do
        teaser_block = TeaserBlock.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TeaserBlock.any_instance.stub(:save).and_return(false)
        put :update, {:id => teaser_block.to_param, :teaser_block => { "topic" => "invalid value" }}, valid_session
        assigns(:teaser_block).should eq(teaser_block)
      end

      it "re-renders the 'edit' template" do
        teaser_block = TeaserBlock.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TeaserBlock.any_instance.stub(:save).and_return(false)
        put :update, {:id => teaser_block.to_param, :teaser_block => { "topic" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested teaser_block" do
      teaser_block = TeaserBlock.create! valid_attributes
      expect {
        delete :destroy, {:id => teaser_block.to_param}, valid_session
      }.to change(TeaserBlock, :count).by(-1)
    end

    it "redirects to the teaser_blocks list" do
      teaser_block = TeaserBlock.create! valid_attributes
      delete :destroy, {:id => teaser_block.to_param}, valid_session
      response.should redirect_to(teaser_blocks_url)
    end
  end

end
